change optimization flags to support Apple M1
nwchemgit/nwchem pull request #326
Opened 2021-02-14 17:45 UTC by jeffhammond

There are two issues to address:
1) a bug in GCC 10: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99092
2) explicit x86/SSE flags that probably don't help at this point anyways.

Signed-off-by: Jeff Hammond <jeff.science@gmail.com>

2021-02-14 17:46 UTC, jeffhammond commented
I don't know if anyone can test on Apple M1 right now but the changes I made here are completely portable.

2021-02-15 19:43 UTC, edoapra requested changes
I can see only one real change, that is the removal of `-fprefetch-loop-arrays` in `FVECTORIZE` ... am I right? The other lines of diff output they seem to be  just cosmetic. Could you submit a PR without the cosmetic changes?

2021-02-15 22:25 UTC, jeffhammond commented
Yeah, I'll fix it, although removing trailing white space is useful for other reasons, because it doesn't show up with git diff.

2021-02-19 00:43 UTC, jeffhammond commented
@edoapra whitespace changes were removed

2021-02-19 01:50 UTC, edoapra approved these changes

2021-02-19 01:51 UTC, edoapra commented
thanks

2021-02-19 01:51 UTC, merged